<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <groupId>com.mobilia</groupId>
    <artifactId>mobilia-backend</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>mobilia-backend</name>
    <description>Mobilia Software technical development test</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <modules>
        <module>domain/model</module>
        <module>domain/usecase</module>

        <module>infrastructure/driven-adapters/r2dbc-mysql</module>
        <module>infrastructure/entry-points/reactive-web</module>

        <module>applications/app-service</module>
    </modules>

</project>