spring.application.name=backend

# R2DBC
spring.r2dbc.url=r2dbc:mysql://localhost:3306/mobilia_db
spring.r2dbc.username=mobilia
spring.r2dbc.password=mobilia_dev
api.contracts.base-path=/api/v1/contracts
# Flyway
spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://localhost:3306/mobilia_db
spring.flyway.user=mobilia
spring.flyway.password=mobilia_dev
spring.flyway.locations=classpath:db/migration

server.port=8080