spring.application.name=backend

# R2DBC
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/mobilia_db}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:mobilia}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:mobilia_dev}

# Flyway
spring.flyway.enabled=true
spring.flyway.url=${SPRING_FLYWAY_URL:jdbc:mysql://localhost:3306/mobilia_db}
spring.flyway.user=${SPRING_FLYWAY_USER:mobilia}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD:mobilia_dev}
spring.flyway.locations=classpath:db/migration

api.contracts.base-path=${API_CONTRACTS_BASE_PATH:/api/v1/contracts}

server.port=${SERVER_PORT:8080}